image:
  name: hashicorp/terraform:0.12.18

stages:
  - validate

tffmt:
  stage: validate
  tags:
    - default
  script:
    - terraform fmt -write=false -diff -check

tfvalidate:
  stage: validate
  tags:
    - default
  script:
    - mv terraform.tfvars.ci terraform.tfvars
    - mv main.tf.ci main.tf
    - terraform init
    - terraform validate
